language: python
#  cmake https://docs.travis-ci.com/user/languages/cpp/
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: sh direct_run.sh